spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/qianshou
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: vod-service
  redis:
    host: 39.101.132.2
    timeout: 5000
server:
  port: 18084
